
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clamav-poc
spec:
  params:
    - name: image-digest
      description: Image digest to scan
      default: quay.io/cvpops/test-index@sha256:50154de7c88e9243afd3dfc767d4db83ff5583786405c35078746f95bb50dea9
  steps:
    - name: extract-and-scan-image
      image: quay.io/jsztuka/worker:v2
      script: |
        cp -r /tmp/clamdb/* /var/lib/clamav
        mkdir -p /tmp/extracted-image && cd /tmp/extracted-image
        oc image extract '$(params.image-digest)'
        clamscan /tmp/extracted-image -ri --max-scansize=250M | tee /tekton/home/clamscan-result.log
        echo "Scan was executed on version: $(clamscan --version)" | tee -a /tekton/home/clamscan-result.log
      volumeMounts:
        - mountPath: /tmp/clamdb
          name: dbfolder
  sidecars:
    - image: quay.io/jsztuka/clam:v3
      name: database
      script: |
        #!/usr/bin/env bash
        cp -r /var/lib/clamav/* /tmp/clamdb
      volumeMounts:
        - mountPath: /tmp/clamdb
          name: dbfolder
  volumes:
    - name: dbfolder
      emptydir: {}